---
kind: Secret
apiVersion: v1
metadata:
  name: {{ include ".helm.fullname" . }}
data:
{{- range $key, $val := .Values.env }}
  {{ $key }}: {{ tpl (pluck $.Values.global.env $val | first | default $val._default) $ | b64enc | quote }}
{{- end }}
