---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ include ".helm.fullname" . }}
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: {{ include ".helm.fullname" . }}
