---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include ".helm.fullname" . }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include ".helm.fullname" . }}
rules:
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - watch
      - get
      - list
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - watch
      - get
      - list
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name:  {{ include ".helm.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include ".helm.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include ".helm.fullname" . }}
    namespace: {{ .Release.Namespace }}
