---
apiVersion: v1
kind: Secret
metadata:
  name: {{ tpl (index .Values.imagePullSecrets 0 "name") $ }}
data:
  .dockerconfigjson: {{ template "getImagePullSecret" .Values.imageCredentials }}
type: kubernetes.io/dockerconfigjson
